title: Kevin McGillivray
markdown: kramdown
permalink: none
description: "My name is Kevin McGillivray. I'm a designer from Wisconsin. I like iterative creativity, simplicity, and tea. My favorite word is 'studio.'"