title: Kevin McGillivray
url: kevinmcgillivray.net
markdown: kramdown
highlighter: pygments
permalink: /:title
description: "Designer, currently making Internet things. I like iterative creativity, simplicity, and tea. My favorite word is 'studio.'"