title: Kevin McGillivray
url: kevinmcgillivray.net
markdown: kramdown
highlighter: pygments
permalink: /:title
description: "Kevin McGillivray is a teacher and web developer from Wisconsin. He writes about creativity, mindfulness, code, and tea."
collections:
  - projects
