title: Kevin McGillivray
markdown: kramdown
highlighter: pygments
permalink: none
description: "Designer, currently making Internet things. I like iterative creativity, simplicity, and tea. My favorite word is 'studio.'"